export const CATEGORY = "CATEGORY"
export const IMAGEID = "IMAGEID"



export const LOGINPAGE = "LOGINPAGE"

export const LOGINSIGNUP = "LOGINSIGNUP"
export const AUTHSUCCESS = "AUTHSUCCESS"
export const AUTHFAIELD = "AUTHFAIELD"
export const AUTHLOGOUT = "AUTHLOGOUT"
export const AUTHLOADING = "AUTHLOADING"


export const FEEDBACKFETCHED = "FEEDBACKFETCHED"
export const FEEDBACKSUCCESS = "FEEDBACKSUCCESS"
export const FEEDBACKFAILED = "FEEDBACKFAILED"