export const images = {
  cars: [
    {
      id: 1,
      name: "Forbes",
      image:
        "https://imageio.forbes.com/specials-images/imageserve/5d35eacaf1176b0008974b54/2020-Chevrolet-Corvette-Stingray/0x0.jpg?format=jpg&crop=4560,2565,x790,y784,safe&width=960",
    },
    {
      id: 2,
      name: "Bugatti",
      image:
        "https://cdn.motor1.com/images/mgl/mrz1e/s1/4x3/coolest-cars-feature.webp",
    },
    {
      id: 3,
      name: "Rolls Royce",
      image:
        "https://www.autocar.co.uk/sites/autocar.co.uk/files/styles/gallery_slide/public/images/car-reviews/first-drives/legacy/rolls_royce_phantom_top_10.jpg?itok=XjL9f1tx",
    },
    {
      id: 4,
      name: "Tesla",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeuLh5RyUR6FDYZi9MQeD7RoQfU90cY67quA&usqp=CAU",
    },
    {
      id: 5,
      name: "Luxury Car",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4M9KI_4aRw3oCydWnNUuQKfvC_yfStPzhoA&usqp=CAU",
    }
  ],
  cities: [
    {
      id: 1,
      name: "London",
      image:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/London_Skyline_%28125508655%29.jpeg/278px-London_Skyline_%28125508655%29.jpeg",
    },
    {
      id: 2,
      name: "Dhaka",
      image:
        "https://t0.gstatic.com/licensed-image?q=tbn:ANd9GcQBIkQTefSlEi3yMXUIM5XPre4FRgSoP8rbsJ39oIHyL_g_uHHyE9CcnQmIalz8kjkV",
    },
    {
      id: 3,
      name: "New York",
      image:
        "http://t3.gstatic.com/images?q=tbn:ANd9GcS0qntvfqyi4-xQzk0TaOqb0IJWUqS_zgVt8-kVxT-Prj5XXNxxh0RF3QZsuQ_Gepk-Ini4",
    },
    {
      id: 4,
      name: "Chicago",
      image:
        "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTVoBAvpW8BeExMudVFN03jan0pK5nuNrkVnt-PC1YWtpqNsjXA",
    },
    {
      id: 5,
      name: "São Paulo",
      image:
        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRT87dkGi0U2ID3FThHvuEygnfr82jLtw93MushBL4OfPxWMCMM",
    },
    {
      id: 6,
      name: "Los Angeles",
      image:
        "https://cdn.britannica.com/22/154122-050-B1D0A7FD/Skyline-Los-Angeles-California.jpg",
    },
    {
      id: 7,
      name: "Beijing",
      image:
        "http://t1.gstatic.com/images?q=tbn:ANd9GcQl1xV8L9V3scdt3J97IMEFBpaOhEsQ6-XeexMUOSKlQfkajc1aMCj5VpOY4OzZLOi9JjCJ",
    },
    {
      id: 8,
      name: "İstanbul",
      image:
        "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTPYmNgFokr2luaMNE_ZtYNG74jXgO2SorDx3rzbpOyHinCuG8e",
    },
    {
      id: 9,
      name: "Tokyo",
      image:
        "https://upload.wikimedia.org/wikipedia/commons/b/b2/Skyscrapers_of_Shinjuku_2009_January.jpg",
    },
  ],
  flags: [
    {
      id: 1,
      name: "Christmas Island",
      image: "https://flagcdn.com/w320/cx.png",
      population: 2072,
      capital: ["Flying Fish Cove"],
      area: 135,
    },
    {
      id: 2,
      name: "Eritrea",
      image: "https://flagcdn.com/w320/er.png",
      population: 5352000,
      capital: ["Asmara"],
      area: 117600,
    },
    {
      id: 3,
      name: "Samoa",
      image: "https://flagcdn.com/w320/ws.png",
      population: 198410,
      capital: ["Apia"],
      area: 2842,
    },
    {
      id: 4,
      name: "North Macedonia",
      image: "https://flagcdn.com/w320/mk.png",
      population: 2077132,
      capital: ["Skopje"],
      area: 25713,
    },
    {
      id: 5,
      name: "Djibouti",
      image: "https://flagcdn.com/w320/dj.png",
      population: 988002,
      capital: ["Djibouti"],
      area: 23200,
    },
    {
      id: 6,
      name: "Jordan",
      image: "https://flagcdn.com/w320/jo.png",
      population: 10203140,
      capital: ["Amman"],
      area: 89342,
    },
    {
      id: 7,
      name: "Pakistan",
      image: "https://flagcdn.com/w320/pk.png",
      population: 220892331,
      capital: ["Islamabad"],
      area: 881912,
    },
    {
      id: 8,
      name: "French Polynesia",
      image: "https://flagcdn.com/w320/pf.png",
      population: 280904,
      capital: ["Papeetē"],
      area: 4167,
    },
    {
      id: 9,
      name: "Ireland",
      image: "https://flagcdn.com/w320/ie.png",
      population: 4994724,
      capital: ["Dublin"],
      area: 70273,
    },
    {
      id: 10,
      name: "Mauritania",
      image: "https://flagcdn.com/w320/mr.png",
      population: 4649660,
      capital: ["Nouakchott"],
      area: 1030700,
    },
    {
      id: 11,
      name: "Denmark",
      image: "https://flagcdn.com/w320/dk.png",
      population: 5831404,
      capital: ["Copenhagen"],
      area: 43094,
    },
    {
      id: 12,
      name: "Namibia",
      image: "https://flagcdn.com/w320/na.png",
      population: 2540916,
      capital: ["Windhoek"],
      area: 825615,
    },
    {
      id: 13,
      name: "Ghana",
      image: "https://flagcdn.com/w320/gh.png",
      population: 31072945,
      capital: ["Accra"],
      area: 238533,
    },
    {
      id: 14,
      name: "South Sudan",
      image: "https://flagcdn.com/w320/ss.png",
      population: 11193729,
      capital: ["Juba"],
      area: 619745,
    },
    {
      id: 15,
      name: "Slovakia",
      image: "https://flagcdn.com/w320/sk.png",
      population: 5458827,
      capital: ["Bratislava"],
      area: 49037,
    },
    {
      id: 16,
      name: "American Samoa",
      image: "https://flagcdn.com/w320/as.png",
      population: 55197,
      capital: ["Pago Pago"],
      area: 199,
    },
    {
      id: 17,
      name: "Moldova",
      image: "https://flagcdn.com/w320/md.png",
      population: 2617820,
      capital: ["Chișinău"],
      area: 33846,
    },
    {
      id: 18,
      name: "North Korea",
      image: "https://flagcdn.com/w320/kp.png",
      population: 25778815,
      capital: ["Pyongyang"],
      area: 120538,
    },
    {
      id: 19,
      name: "Macau",
      image: "https://flagcdn.com/w320/mo.png",
      population: 649342,
      area: 30,
    },
    {
      id: 20,
      name: "Turks and Caicos Islands",
      image: "https://flagcdn.com/w320/tc.png",
      population: 38718,
      capital: ["Cockburn Town"],
      area: 948,
    },
    {
      id: 21,
      name: "Seychelles",
      image: "https://flagcdn.com/w320/sc.png",
      population: 98462,
      capital: ["Victoria"],
      area: 452,
    },
    {
      id: 22,
      name: "Armenia",
      image: "https://flagcdn.com/w320/am.png",
      population: 2963234,
      capital: ["Yerevan"],
      area: 29743,
    },
    {
      id: 23,
      name: "Curaçao",
      image: "https://flagcdn.com/w320/cw.png",
      population: 155014,
      capital: ["Willemstad"],
      area: 444,
    },
    {
      id: 24,
      name: "Guadeloupe",
      image: "https://flagcdn.com/w320/gp.png",
      population: 400132,
      capital: ["Basse-Terre"],
      area: 1628,
    },
    {
      id: 25,
      name: "British Indian Ocean Territory",
      image: "https://flagcdn.com/w320/io.png",
      population: 3000,
      capital: ["Diego Garcia"],
      area: 60,
    },
    {
      id: 26,
      name: "Equatorial Guinea",
      image: "https://flagcdn.com/w320/gq.png",
      population: 1402985,
      capital: ["Malabo"],
      area: 28051,
    },
    {
      id: 27,
      name: "Syria",
      image: "https://flagcdn.com/w320/sy.png",
      population: 17500657,
      capital: ["Damascus"],
      area: 185180,
    },
    {
      id: 28,
      name: "Angola",
      image: "https://flagcdn.com/w320/ao.png",
      population: 32866268,
      capital: ["Luanda"],
      area: 1246700,
    },
    {
      id: 29,
      name: "Tajikistan",
      image: "https://flagcdn.com/w320/tj.png",
      population: 9537642,
      capital: ["Dushanbe"],
      area: 143100,
    },
    {
      id: 30,
      name: "Venezuela",
      image: "https://flagcdn.com/w320/ve.png",
      population: 28435943,
      capital: ["Caracas"],
      area: 916445,
    },
    {
      id: 31,
      name: "United States Minor Outlying Islands",
      image: "https://flagcdn.com/w320/um.png",
      population: 300,
      capital: ["Washington DC"],
      area: 34.2,
    },
    {
      id: 32,
      name: "Åland Islands",
      image: "https://flagcdn.com/w320/ax.png",
      population: 29458,
      capital: ["Mariehamn"],
      area: 1580,
    },
    {
      id: 33,
      name: "Poland",
      image: "https://flagcdn.com/w320/pl.png",
      population: 37950802,
      capital: ["Warsaw"],
      area: 312679,
    },
    {
      id: 34,
      name: "Saudi Arabia",
      image: "https://flagcdn.com/w320/sa.png",
      population: 34813867,
      capital: ["Riyadh"],
      area: 2149690,
    },
    {
      id: 35,
      name: "Republic of the Congo",
      image: "https://flagcdn.com/w320/cg.png",
      population: 5657000,
      capital: ["Brazzaville"],
      area: 342000,
    },
    {
      id: 36,
      name: "Bosnia and Herzegovina",
      image: "https://flagcdn.com/w320/ba.png",
      population: 3280815,
      capital: ["Sarajevo"],
      area: 51209,
    },
    {
      id: 37,
      name: "United States Virgin Islands",
      image: "https://flagcdn.com/w320/vi.png",
      population: 106290,
      capital: ["Charlotte Amalie"],
      area: 347,
    },
    {
      id: 38,
      name: "New Caledonia",
      image: "https://flagcdn.com/w320/nc.png",
      population: 271960,
      capital: ["Nouméa"],
      area: 18575,
    },
    {
      id: 39,
      name: "San Marino",
      image: "https://flagcdn.com/w320/sm.png",
      population: 33938,
      capital: ["City of San Marino"],
      area: 61,
    },
    {
      id: 40,
      name: "Czechia",
      image: "https://flagcdn.com/w320/cz.png",
      population: 10698896,
      capital: ["Prague"],
      area: 78865,
    },
    {
      id: 41,
      name: "Guatemala",
      image: "https://flagcdn.com/w320/gt.png",
      population: 16858333,
      capital: ["Guatemala City"],
      area: 108889,
    },
    {
      id: 42,
      name: "South Korea",
      image: "https://flagcdn.com/w320/kr.png",
      population: 51780579,
      capital: ["Seoul"],
      area: 100210,
    },
    {
      id: 43,
      name: "Estonia",
      image: "https://flagcdn.com/w320/ee.png",
      population: 1331057,
      capital: ["Tallinn"],
      area: 45227,
    },
    {
      id: 44,
      name: "Nepal",
      image: "https://flagcdn.com/w320/np.png",
      population: 29136808,
      capital: ["Kathmandu"],
      area: 147181,
    },
    {
      id: 45,
      name: "Kosovo",
      image: "https://flagcdn.com/w320/xk.png",
      population: 1775378,
      capital: ["Pristina"],
      area: 10908,
    },
    {
      id: 46,
      name: "Botswana",
      image: "https://flagcdn.com/w320/bw.png",
      population: 2351625,
      capital: ["Gaborone"],
      area: 582000,
    },
    {
      id: 47,
      name: "Philippines",
      image: "https://flagcdn.com/w320/ph.png",
      population: 109581085,
      capital: ["Manila"],
      area: 342353,
    },
    {
      id: 48,
      name: "Saint Pierre and Miquelon",
      image: "https://flagcdn.com/w320/pm.png",
      population: 6069,
      capital: ["Saint-Pierre"],
      area: 242,
    },
    {
      id: 49,
      name: "Iraq",
      image: "https://flagcdn.com/w320/iq.png",
      population: 40222503,
      capital: ["Baghdad"],
      area: 438317,
    },
    {
      id: 50,
      name: "Lebanon",
      image: "https://flagcdn.com/w320/lb.png",
      population: 6825442,
      capital: ["Beirut"],
      area: 10452,
    },
    {
      id: 51,
      name: "Burundi",
      image: "https://flagcdn.com/w320/bi.png",
      population: 11890781,
      capital: ["Gitega"],
      area: 27834,
    },
    {
      id: 52,
      name: "Mongolia",
      image: "https://flagcdn.com/w320/mn.png",
      population: 3278292,
      capital: ["Ulan Bator"],
      area: 1564110,
    },
    {
      id: 53,
      name: "Faroe Islands",
      image: "https://flagcdn.com/w320/fo.png",
      population: 48865,
      capital: ["Tórshavn"],
      area: 1393,
    },
    {
      id: 54,
      name: "Paraguay",
      image: "https://flagcdn.com/w320/py.png",
      population: 7132530,
      capital: ["Asunción"],
      area: 406752,
    },
    {
      id: 63,
      name: "Sint Maarten",
      image: "https://flagcdn.com/w320/sx.png",
      population: 40812,
      capital: ["Philipsburg"],
      area: 34,
    },
    {
      id: 64,
      name: "Chad",
      image: "https://flagcdn.com/w320/td.png",
      population: 16425859,
      capital: ["N'Djamena"],
      area: 1284000,
    },
    {
      id: 65,
      name: "Finland",
      image: "https://flagcdn.com/w320/fi.png",
      population: 5530719,
      capital: ["Helsinki"],
      area: 338424,
    },
    {
      id: 66,
      name: "Panama",
      image: "https://flagcdn.com/w320/pa.png",
      population: 4314768,
      capital: ["Panama City"],
      area: 75417,
    },
    {
      id: 67,
      name: "Palestine",
      image: "https://flagcdn.com/w320/ps.png",
      population: 4803269,
      capital: ["Ramallah", "Jerusalem"],
      area: 6220,
    },
    {
      id: 68,
      name: "Yemen",
      image: "https://flagcdn.com/w320/ye.png",
      population: 29825968,
      capital: ["Sana'a"],
      area: 527968,
    },
    {
      id: 69,
      name: "Brazil",
      image: "https://flagcdn.com/w320/br.png",
      population: 212559409,
      capital: ["Brasília"],
      area: 8515767,
    },
    {
      id: 70,
      name: "Nigeria",
      image: "https://flagcdn.com/w320/ng.png",
      population: 206139587,
      capital: ["Abuja"],
      area: 923768,
    },
    {
      id: 71,
      name: "Palau",
      image: "https://flagcdn.com/w320/pw.png",
      population: 18092,
      capital: ["Ngerulmud"],
      area: 459,
    },
    {
      id: 72,
      name: "Japan",
      image: "https://flagcdn.com/w320/jp.png",
      population: 125836021,
      capital: ["Tokyo"],
      area: 377930,
    },
    {
      id: 73,
      name: "Tanzania",
      image: "https://flagcdn.com/w320/tz.png",
      population: 59734213,
      capital: ["Dodoma"],
      area: 945087,
    },
    {
      id: 74,
      name: "Kazakhstan",
      image: "https://flagcdn.com/w320/kz.png",
      population: 18754440,
      capital: ["Nur-Sultan"],
      area: 2724900,
    },
    {
      id: 75,
      name: "Portugal",
      image: "https://flagcdn.com/w320/pt.png",
      population: 10305564,
      capital: ["Lisbon"],
      area: 92090,
    },
    {
      id: 76,
      name: "South Georgia",
      image: "https://flagcdn.com/w320/gs.png",
      population: 30,
      capital: ["King Edward Point"],
      area: 3903,
    },
    {
      id: 77,
      name: "Sri Lanka",
      image: "https://flagcdn.com/w320/lk.png",
      population: 21919000,
      capital: ["Sri Jayawardenepura Kotte"],
      area: 65610,
    },
    {
      id: 78,
      name: "Germany",
      image: "https://flagcdn.com/w320/de.png",
      population: 83240525,
      capital: ["Berlin"],
      area: 357114,
    },
    {
      id: 79,
      name: "Western Sahara",
      image: "https://flagcdn.com/w320/eh.png",
      population: 510713,
      capital: ["El Aaiún"],
      area: 266000,
    },
    {
      id: 80,
      name: "Myanmar",
      image: "https://flagcdn.com/w320/mm.png",
      population: 54409794,
      capital: ["Naypyidaw"],
      area: 676578,
    },
    {
      id: 81,
      name: "Colombia",
      image: "https://flagcdn.com/w320/co.png",
      population: 50882884,
      capital: ["Bogotá"],
      area: 1141748,
    },
    {
      id: 82,
      name: "Peru",
      image: "https://flagcdn.com/w320/pe.png",
      population: 32971846,
      capital: ["Lima"],
      area: 1285216,
    },
    {
      id: 83,
      name: "Senegal",
      image: "https://flagcdn.com/w320/sn.png",
      population: 16743930,
      capital: ["Dakar"],
      area: 196722,
    },
    {
      id: 84,
      name: "Kyrgyzstan",
      image: "https://flagcdn.com/w320/kg.png",
      population: 6591600,
      capital: ["Bishkek"],
      area: 199951,
    },
    {
      id: 85,
      name: "China",
      image: "https://flagcdn.com/w320/cn.png",
      population: 1402112000,
      capital: ["Beijing"],
      area: 9706961,
    },
    {
      id: 86,
      name: "Afghanistan",
      image:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png",
      population: 40218234,
      capital: ["Kabul"],
      area: 652230,
    },
    {
      id: 87,
      name: "Turkey",
      image: "https://flagcdn.com/w320/tr.png",
      population: 84339067,
      capital: ["Ankara"],
      area: 783562,
    },
    {
      id: 88,
      name: "Liberia",
      image: "https://flagcdn.com/w320/lr.png",
      population: 5057677,
      capital: ["Monrovia"],
      area: 111369,
    },
    {
      id: 89,
      name: "South Africa",
      image: "https://flagcdn.com/w320/za.png",
      population: 59308690,
      capital: ["Pretoria", "Bloemfontein", "Cape Town"],
      area: 1221037,
    },
    {
      id: 90,
      name: "Chile",
      image: "https://flagcdn.com/w320/cl.png",
      population: 19116209,
      capital: ["Santiago"],
      area: 756102,
    },
    {
      id: 91,
      name: "Malta",
      image: "https://flagcdn.com/w320/mt.png",
      population: 525285,
      capital: ["Valletta"],
      area: 316,
    },
    {
      id: 95,
      name: "Iceland",
      image: "https://flagcdn.com/w320/is.png",
      population: 366425,
      capital: ["Reykjavik"],
      area: 103000,
    },
    {
      id: 96,
      name: "Gambia",
      image: "https://flagcdn.com/w320/gm.png",
      population: 2416664,
      capital: ["Banjul"],
      area: 10689,
    },
    {
      id: 97,
      name: "Vanuatu",
      image: "https://flagcdn.com/w320/vu.png",
      population: 307150,
      capital: ["Port Vila"],
      area: 12189,
    },
    {
      id: 98,
      name: "Uruguay",
      image: "https://flagcdn.com/w320/uy.png",
      population: 3473727,
      capital: ["Montevideo"],
      area: 181034,
    },
    {
      id: 99,
      name: "Oman",
      image: "https://flagcdn.com/w320/om.png",
      population: 5106622,
      capital: ["Muscat"],
      area: 309500,
    },
    {
      id: 100,
      name: "Sudan",
      image: "https://flagcdn.com/w320/sd.png",
      population: 43849269,
      capital: ["Khartoum"],
      area: 1886068,
    },
    {
      id: 101,
      name: "India",
      image: "https://flagcdn.com/w320/in.png",
      population: 1380004385,
      capital: ["New Delhi"],
      area: 3287590,
    },
    {
      id: 102,
      name: "Laos",
      image: "https://flagcdn.com/w320/la.png",
      population: 7275556,
      capital: ["Vientiane"],
      area: 236800,
    },
    {
      id: 103,
      name: "Aruba",
      image: "https://flagcdn.com/w320/aw.png",
      population: 106766,
      capital: ["Oranjestad"],
      area: 180,
    },
    {
      id: 104,
      name: "Martinique",
      image: "https://flagcdn.com/w320/mq.png",
      population: 378243,
      capital: ["Fort-de-France"],
      area: 1128,
    },
    {
      id: 105,
      name: "Comoros",
      image: "https://flagcdn.com/w320/km.png",
      population: 869595,
      capital: ["Moroni"],
      area: 1862,
    },
    {
      id: 106,
      name: "Spain",
      image: "https://flagcdn.com/w320/es.png",
      population: 47351567,
      capital: ["Madrid"],
      area: 505992,
    },
    {
      id: 107,
      name: "Antigua and Barbuda",
      image: "https://flagcdn.com/w320/ag.png",
      population: 97928,
      capital: ["Saint John's"],
      area: 442,
    },
    {
      id: 108,
      name: "Uzbekistan",
      image: "https://flagcdn.com/w320/uz.png",
      population: 34232050,
      capital: ["Tashkent"],
      area: 447400,
    },
    {
      id: 109,
      name: "Maldives",
      image: "https://flagcdn.com/w320/mv.png",
      population: 540542,
      capital: ["Malé"],
      area: 300,
    },
    {
      id: 110,
      name: "Gibraltar",
      image: "https://flagcdn.com/w320/gi.png",
      population: 33691,
      capital: ["Gibraltar"],
      area: 6,
    },
    {
      id: 111,
      name: "Indonesia",
      image: "https://flagcdn.com/w320/id.png",
      population: 273523621,
      capital: ["Jakarta"],
      area: 1904569,
    },
    {
      id: 112,
      name: "Pitcairn Islands",
      image: "https://flagcdn.com/w320/pn.png",
      population: 56,
      capital: ["Adamstown"],
      area: 47,
    },
    {
      id: 113,
      name: "Vietnam",
      image: "https://flagcdn.com/w320/vn.png",
      population: 97338583,
      capital: ["Hanoi"],
      area: 331212,
    },
    {
      id: 114,
      name: "Malaysia",
      image: "https://flagcdn.com/w320/my.png",
      population: 32365998,
      capital: ["Kuala Lumpur"],
      area: 330803,
    },
    {
      id: 115,
      name: "Cook Islands",
      image: "https://flagcdn.com/w320/ck.png",
      population: 18100,
      capital: ["Avarua"],
      area: 236,
    },
    {
      id: 116,
      name: "Eswatini",
      image: "https://flagcdn.com/w320/sz.png",
      population: 1160164,
      capital: ["Mbabane"],
      area: 17364,
    },
    {
      id: 117,
      name: "Uganda",
      image: "https://flagcdn.com/w320/ug.png",
      population: 45741000,
      capital: ["Kampala"],
      area: 241550,
    },
    {
      id: 118,
      name: "Madagascar",
      image: "https://flagcdn.com/w320/mg.png",
      population: 27691019,
      capital: ["Antananarivo"],
      area: 587041,
    },
    {
      id: 119,
      name: "Fiji",
      image: "https://flagcdn.com/w320/fj.png",
      population: 896444,
      capital: ["Suva"],
      area: 18272,
    },
    {
      id: 120,
      name: "Norway",
      image: "https://flagcdn.com/w320/no.png",
      population: 5379475,
      capital: ["Oslo"],
      area: 323802,
    },
    {
      id: 121,
      name: "Antarctica",
      image: "https://flagcdn.com/w320/aq.png",
      population: 1000,
      area: 14000000,
    },
    {
      id: 122,
      name: "Bouvet Island",
      image: "https://flagcdn.com/w320/bv.png",
      population: 0,
      area: 49,
    },
    {
      id: 123,
      name: "Cyprus",
      image: "https://flagcdn.com/w320/cy.png",
      population: 1207361,
      capital: ["Nicosia"],
      area: 9251,
    },
    {
      id: 124,
      name: "Taiwan",
      image: "https://flagcdn.com/w320/tw.png",
      population: 23503349,
      capital: ["Taipei"],
      area: 36193,
    },
    {
      id: 133,
      name: "Saint Helena, Ascension and Tristan da Cunha",
      image: "https://flagcdn.com/w320/sh.png",
      population: 53192,
      capital: ["Jamestown"],
      area: 394,
    },
    {
      id: 134,
      name: "United Arab Emirates",
      image: "https://flagcdn.com/w320/ae.png",
      population: 9890400,
      capital: ["Abu Dhabi"],
      area: 83600,
    },
    {
      id: 135,
      name: "Bermuda",
      image: "https://flagcdn.com/w320/bm.png",
      population: 63903,
      capital: ["Hamilton"],
      area: 54,
    },
    {
      id: 136,
      name: "Monaco",
      image: "https://flagcdn.com/w320/mc.png",
      population: 39244,
      capital: ["Monaco"],
      area: 2.02,
    },
    {
      id: 137,
      name: "Cuba",
      image: "https://flagcdn.com/w320/cu.png",
      population: 11326616,
      capital: ["Havana"],
      area: 109884,
    },
    {
      id: 138,
      name: "Hong Kong",
      image: "https://flagcdn.com/w320/hk.png",
      population: 7500700,
      capital: ["City of Victoria"],
      area: 1104,
    },
    {
      id: 139,
      name: "Northern Mariana Islands",
      image: "https://flagcdn.com/w320/mp.png",
      population: 57557,
      capital: ["Saipan"],
      area: 464,
    },
    {
      id: 140,
      name: "Togo",
      image: "https://flagcdn.com/w320/tg.png",
      population: 8278737,
      capital: ["Lomé"],
      area: 56785,
    },
    {
      id: 141,
      name: "Luxembourg",
      image: "https://flagcdn.com/w320/lu.png",
      population: 632275,
      capital: ["Luxembourg"],
      area: 2586,
    },
    {
      id: 142,
      name: "Mauritius",
      image: "https://flagcdn.com/w320/mu.png",
      population: 1265740,
      capital: ["Port Louis"],
      area: 2040,
    },
    {
      id: 143,
      name: "Argentina",
      image: "https://flagcdn.com/w320/ar.png",
      population: 45376763,
      capital: ["Buenos Aires"],
      area: 2780400,
    },
    {
      id: 144,
      name: "Grenada",
      image: "https://flagcdn.com/w320/gd.png",
      population: 112519,
      capital: ["St. George's"],
      area: 344,
    },
    {
      id: 145,
      name: "Nicaragua",
      image: "https://flagcdn.com/w320/ni.png",
      population: 6624554,
      capital: ["Managua"],
      area: 130373,
    },
    {
      id: 146,
      name: "Niue",
      image: "https://flagcdn.com/w320/nu.png",
      population: 1470,
      capital: ["Alofi"],
      area: 260,
    },
    {
      id: 147,
      name: "Ukraine",
      image: "https://flagcdn.com/w320/ua.png",
      population: 44134693,
      capital: ["Kyiv"],
      area: 603500,
    },
    {
      id: 148,
      name: "Guyana",
      image: "https://flagcdn.com/w320/gy.png",
      population: 786559,
      capital: ["Georgetown"],
      area: 214969,
    },
    {
      id: 149,
      name: "Niger",
      image: "https://flagcdn.com/w320/ne.png",
      population: 24206636,
      capital: ["Niamey"],
      area: 1267000,
    },
    {
      id: 150,
      name: "Benin",
      image: "https://flagcdn.com/w320/bj.png",
      population: 12123198,
      capital: ["Porto-Novo"],
      area: 112622,
    },
    {
      id: 151,
      name: "Saint Lucia",
      image: "https://flagcdn.com/w320/lc.png",
      population: 183629,
      capital: ["Castries"],
      area: 616,
    },
    {
      id: 152,
      name: "Tuvalu",
      image: "https://flagcdn.com/w320/tv.png",
      population: 11792,
      capital: ["Funafuti"],
      area: 26,
    },
    {
      id: 153,
      name: "Norfolk Island",
      image: "https://flagcdn.com/w320/nf.png",
      population: 2302,
      capital: ["Kingston"],
      area: 36,
    },
    {
      id: 154,
      name: "Egypt",
      image: "https://flagcdn.com/w320/eg.png",
      population: 102334403,
      capital: ["Cairo"],
      area: 1002450,
    },
    {
      id: 155,
      name: "Saint Kitts and Nevis",
      image: "https://flagcdn.com/w320/kn.png",
      population: 53192,
      capital: ["Basseterre"],
      area: 261,
    },
    {
      id: 156,
      name: "Lesotho",
      image: "https://flagcdn.com/w320/ls.png",
      population: 2142252,
      capital: ["Maseru"],
      area: 30355,
    },
    {
      id: 157,
      name: "Tonga",
      image: "https://flagcdn.com/w320/to.png",
      population: 105697,
      capital: ["Nuku'alofa"],
      area: 747,
    },
    {
      id: 158,
      name: "Georgia",
      image: "https://flagcdn.com/w320/ge.png",
      population: 3714000,
      capital: ["Tbilisi"],
      area: 69700,
    },
    {
      id: 159,
      name: "Ethiopia",
      image: "https://flagcdn.com/w320/et.png",
      population: 114963583,
      capital: ["Addis Ababa"],
      area: 1104300,
    },
    {
      id: 160,
      name: "Dominican Republic",
      image: "https://flagcdn.com/w320/do.png",
      population: 10847904,
      capital: ["Santo Domingo"],
      area: 48671,
    },
    {
      id: 161,
      name: "Saint Vincent and the Grenadines",
      image: "https://flagcdn.com/w320/vc.png",
      population: 110947,
      capital: ["Kingstown"],
      area: 389,
    },
    {
      id: 164,
      name: "Morocco",
      image: "https://flagcdn.com/w320/ma.png",
      population: 36910558,
      capital: ["Rabat"],
      area: 446550,
    },
    {
      id: 165,
      name: "Haiti",
      image: "https://flagcdn.com/w320/ht.png",
      population: 11402533,
      capital: ["Port-au-Prince"],
      area: 27750,
    },
    {
      id: 166,
      name: "Mayotte",
      image: "https://flagcdn.com/w320/yt.png",
      population: 226915,
      capital: ["Mamoudzou"],
      area: 374,
    },
    {
      id: 167,
      name: "Burkina Faso",
      image: "https://flagcdn.com/w320/bf.png",
      population: 20903278,
      capital: ["Ouagadougou"],
      area: 272967,
    },
    {
      id: 168,
      name: "Bangladesh",
      image: "https://flagcdn.com/w320/bd.png",
      population: 164689383,
      capital: ["Dhaka"],
      area: 147570,
    },
    {
      id: 169,
      name: "Kuwait",
      image: "https://flagcdn.com/w320/kw.png",
      population: 4270563,
      capital: ["Kuwait City"],
      area: 17818,
    },
    {
      id: 170,
      name: "Réunion",
      image: "https://flagcdn.com/w320/re.png",
      population: 840974,
      capital: ["Saint-Denis"],
      area: 2511,
    },
    {
      id: 171,
      name: "Jamaica",
      image: "https://flagcdn.com/w320/jm.png",
      population: 2961161,
      capital: ["Kingston"],
      area: 10991,
    },
    {
      id: 172,
      name: "Romania",
      image: "https://flagcdn.com/w320/ro.png",
      population: 19286123,
      capital: ["Bucharest"],
      area: 238391,
    },
    {
      id: 173,
      name: "São Tomé and Príncipe",
      image: "https://flagcdn.com/w320/st.png",
      population: 219161,
      capital: ["São Tomé"],
      area: 964,
    },
    {
      id: 174,
      name: "Bahamas",
      image: "https://flagcdn.com/w320/bs.png",
      population: 393248,
      capital: ["Nassau"],
      area: 13943,
    },
    {
      id: 175,
      name: "Mexico",
      image: "https://flagcdn.com/w320/mx.png",
      population: 128932753,
      capital: ["Mexico City"],
      area: 1964375,
    },
    {
      id: 176,
      name: "Saint Martin",
      image: "https://flagcdn.com/w320/mf.png",
      population: 38659,
      capital: ["Marigot"],
      area: 53,
    },
    {
      id: 177,
      name: "El Salvador",
      image: "https://flagcdn.com/w320/sv.png",
      population: 6486201,
      capital: ["San Salvador"],
      area: 21041,
    },
    {
      id: 178,
      name: "Saint Barthélemy",
      image: "https://flagcdn.com/w320/bl.png",
      population: 4255,
      capital: ["Gustavia"],
      area: 21,
    },
    {
      id: 179,
      name: "Micronesia",
      image: "https://flagcdn.com/w320/fm.png",
      population: 115021,
      capital: ["Palikir"],
      area: 702,
    },
    {
      id: 180,
      name: "Turkmenistan",
      image: "https://flagcdn.com/w320/tm.png",
      population: 6031187,
      capital: ["Ashgabat"],
      area: 488100,
    },
    {
      id: 181,
      name: "Anguilla",
      image: "https://flagcdn.com/w320/ai.png",
      population: 13452,
      capital: ["The Valley"],
      area: 91,
    },
    {
      id: 182,
      name: "Central African Republic",
      image: "https://flagcdn.com/w320/cf.png",
      population: 4829764,
      capital: ["Bangui"],
      area: 622984,
    },
    {
      id: 183,
      name: "Suriname",
      image: "https://flagcdn.com/w320/sr.png",
      population: 586634,
      capital: ["Paramaribo"],
      area: 163820,
    },
    {
      id: 184,
      name: "Belgium",
      image: "https://flagcdn.com/w320/be.png",
      population: 11555997,
      capital: ["Brussels"],
      area: 30528,
    },
    {
      id: 185,
      name: "Sweden",
      image: "https://flagcdn.com/w320/se.png",
      population: 10353442,
      capital: ["Stockholm"],
      area: 450295,
    },
    {
      id: 186,
      name: "Bolivia",
      image: "https://flagcdn.com/w320/bo.png",
      population: 11673029,
      capital: ["Sucre"],
      area: 1098581,
    },
    {
      id: 187,
      name: "Montenegro",
      image: "https://flagcdn.com/w320/me.png",
      population: 621718,
      capital: ["Podgorica"],
      area: 13812,
    },
    {
      id: 188,
      name: "Mozambique",
      image: "https://flagcdn.com/w320/mz.png",
      population: 31255435,
      capital: ["Maputo"],
      area: 801590,
    },
    {
      id: 189,
      name: "Latvia",
      image: "https://flagcdn.com/w320/lv.png",
      population: 1901548,
      capital: ["Riga"],
      area: 64559,
    },
    {
      id: 190,
      name: "Malawi",
      image: "https://flagcdn.com/w320/mw.png",
      population: 19129955,
      capital: ["Lilongwe"],
      area: 118484,
    },
    {
      id: 191,
      name: "Mali",
      image: "https://flagcdn.com/w320/ml.png",
      population: 20250834,
      capital: ["Bamako"],
      area: 1240192,
    },
    {
      id: 192,
      name: "Vatican City",
      image: "https://flagcdn.com/w320/va.png",
      population: 451,
      capital: ["Vatican City"],
      area: 0.44,
    },
    {
      id: 193,
      name: "Montserrat",
      image: "https://flagcdn.com/w320/ms.png",
      population: 4922,
      capital: ["Plymouth"],
      area: 102,
    },
    {
      id: 194,
      name: "Austria",
      image: "https://flagcdn.com/w320/at.png",
      population: 8917205,
      capital: ["Vienna"],
      area: 83871,
    },
    {
      id: 195,
      name: "Albania",
      image: "https://flagcdn.com/w320/al.png",
      population: 2837743,
      capital: ["Tirana"],
      area: 28748,
    },
    {
      id: 196,
      name: "British Virgin Islands",
      image: "https://flagcdn.com/w320/vg.png",
      population: 30237,
      capital: ["Road Town"],
      area: 151,
    },
    {
      id: 197,
      name: "Zambia",
      image: "https://flagcdn.com/w320/zm.png",
      population: 18383956,
      capital: ["Lusaka"],
      area: 752612,
    },
    {
      id: 198,
      name: "French Guiana",
      image: "https://flagcdn.com/w320/gf.png",
      population: 254541,
      capital: ["Cayenne"],
      area: 83534,
    },
    {
      id: 199,
      name: "Liechtenstein",
      image: "https://flagcdn.com/w320/li.png",
      population: 38137,
      capital: ["Vaduz"],
      area: 160,
    },
    {
      id: 200,
      name: "Qatar",
      image: "https://flagcdn.com/w320/qa.png",
      population: 2881060,
      capital: ["Doha"],
      area: 11586,
    },
    {
      id: 201,
      name: "Solomon Islands",
      image: "https://flagcdn.com/w320/sb.png",
      population: 686878,
      capital: ["Honiara"],
      area: 28896,
    },
    {
      id: 202,
      name: "Nauru",
      image: "https://flagcdn.com/w320/nr.png",
      population: 10834,
      capital: ["Yaren"],
      area: 21,
    },
    {
      id: 203,
      name: "Greece",
      image: "https://flagcdn.com/w320/gr.png",
      population: 10715549,
      capital: ["Athens"],
      area: 131990,
    },
    {
      id: 204,
      name: "Libya",
      image: "https://flagcdn.com/w320/ly.png",
      population: 6871287,
      capital: ["Tripoli"],
      area: 1759540,
    },
    {
      id: 205,
      name: "Guinea-Bissau",
      image: "https://flagcdn.com/w320/gw.png",
      population: 1967998,
      capital: ["Bissau"],
      area: 36125,
    },
    {
      id: 206,
      name: "Barbados",
      image: "https://flagcdn.com/w320/bb.png",
      population: 287371,
      capital: ["Bridgetown"],
      area: 430,
    },
    {
      id: 207,
      name: "Honduras",
      image: "https://flagcdn.com/w320/hn.png",
      population: 9904608,
      capital: ["Tegucigalpa"],
      area: 112492,
    },
    {
      id: 208,
      name: "Somalia",
      image: "https://flagcdn.com/w320/so.png",
      population: 15893219,
      capital: ["Mogadishu"],
      area: 637657,
    },
    {
      id: 209,
      name: "Cayman Islands",
      image: "https://flagcdn.com/w320/ky.png",
      population: 65720,
      capital: ["George Town"],
      area: 264,
    },
    {
      id: 210,
      name: "Italy",
      image: "https://flagcdn.com/w320/it.png",
      population: 59554023,
      capital: ["Rome"],
      area: 301336,
    },
    {
      id: 211,
      name: "Wallis and Futuna",
      image: "https://flagcdn.com/w320/wf.png",
      population: 11750,
      capital: ["Mata-Utu"],
      area: 142,
    },
    {
      id: 212,
      name: "Andorra",
      image: "https://flagcdn.com/w320/ad.png",
      population: 77265,
      capital: ["Andorra la Vella"],
      area: 468,
    },
    {
      id: 213,
      name: "Ecuador",
      image: "https://flagcdn.com/w320/ec.png",
      population: 17643060,
      capital: ["Quito"],
      area: 276841,
    },
    {
      id: 214,
      name: "Kenya",
      image: "https://flagcdn.com/w320/ke.png",
      population: 53771300,
      capital: ["Nairobi"],
      area: 580367,
    },
    {
      id: 215,
      name: "Bahrain",
      image: "https://flagcdn.com/w320/bh.png",
      population: 1701583,
      capital: ["Manama"],
      area: 765,
    },
    {
      id: 216,
      name: "United Kingdom",
      image: "https://flagcdn.com/w320/gb.png",
      population: 67215293,
      capital: ["London"],
      area: 242900,
    },
    {
      id: 217,
      name: "Guinea",
      image: "https://flagcdn.com/w320/gn.png",
      population: 13132792,
      capital: ["Conakry"],
      area: 245857,
    },
    {
      id: 218,
      name: "Heard Island and McDonald Islands",
      image: "https://flagcdn.com/w320/hm.png",
      population: 0,
      area: 412,
    },
    {
      id: 219,
      name: "Russia",
      image: "https://flagcdn.com/w320/ru.png",
      population: 144104080,
      capital: ["Moscow"],
      area: 17098242,
    },
    {
      id: 220,
      name: "Brunei",
      image: "https://flagcdn.com/w320/bn.png",
      population: 437483,
      capital: ["Bandar Seri Begawan"],
      area: 5765,
    },
    {
      id: 221,
      name: "Zimbabwe",
      image: "https://flagcdn.com/w320/zw.png",
      population: 14862927,
      capital: ["Harare"],
      area: 390757,
    },
    {
      id: 222,
      name: "Guam",
      image: "https://flagcdn.com/w320/gu.png",
      population: 168783,
      capital: ["Hagåtña"],
      area: 549,
    },
    {
      id: 223,
      name: "Australia",
      image: "https://flagcdn.com/w320/au.png",
      population: 25687041,
      capital: ["Canberra"],
      area: 7692024,
    },
    {
      id: 224,
      name: "Slovenia",
      image: "https://flagcdn.com/w320/si.png",
      population: 2100126,
      capital: ["Ljubljana"],
      area: 20273,
    },
    {
      id: 225,
      name: "Belarus",
      image: "https://flagcdn.com/w320/by.png",
      population: 9398861,
      capital: ["Minsk"],
      area: 207600,
    },
    {
      id: 226,
      name: "Thailand",
      image: "https://flagcdn.com/w320/th.png",
      population: 69799978,
      capital: ["Bangkok"],
      area: 513120,
    },
    {
      id: 227,
      name: "New Zealand",
      image: "https://flagcdn.com/w320/nz.png",
      population: 5084300,
      capital: ["Wellington"],
      area: 270467,
    },
    {
      id: 228,
      name: "Tunisia",
      image: "https://flagcdn.com/w320/tn.png",
      population: 11818618,
      capital: ["Tunis"],
      area: 163610,
    },
    {
      id: 229,
      name: "Marshall Islands",
      image: "https://flagcdn.com/w320/mh.png",
      population: 59194,
      capital: ["Majuro"],
      area: 181,
    },
    {
      id: 230,
      name: "Sierra Leone",
      image: "https://flagcdn.com/w320/sl.png",
      population: 7976985,
      capital: ["Freetown"],
      area: 71740,
    },
    {
      id: 231,
      name: "Bhutan",
      image: "https://flagcdn.com/w320/bt.png",
      population: 771612,
      capital: ["Thimphu"],
      area: 38394,
    },
    {
      id: 232,
      name: "United States",
      image: "https://flagcdn.com/w320/us.png",
      population: 329484123,
      capital: ["Washington, D.C."],
      area: 9372610,
    },
    {
      id: 233,
      name: "Switzerland",
      image: "https://flagcdn.com/w320/ch.png",
      population: 8654622,
      capital: ["Bern"],
      area: 41284,
    },
    {
      id: 234,
      name: "Falkland Islands",
      image: "https://flagcdn.com/w320/fk.png",
      population: 2563,
      capital: ["Stanley"],
      area: 12173,
    },
    {
      id: 235,
      name: "Cocos (Keeling) Islands",
      image: "https://flagcdn.com/w320/cc.png",
      population: 544,
      capital: ["West Island"],
      area: 14,
    },
    {
      id: 236,
      name: "Gabon",
      image: "https://flagcdn.com/w320/ga.png",
      population: 2225728,
      capital: ["Libreville"],
      area: 267668,
    },
    {
      id: 237,
      name: "Dominica",
      image: "https://flagcdn.com/w320/dm.png",
      population: 71991,
      capital: ["Roseau"],
      area: 751,
    },
    {
      id: 238,
      name: "Canada",
      image: "https://flagcdn.com/w320/ca.png",
      population: 38005238,
      capital: ["Ottawa"],
      area: 9984670,
    },
    {
      id: 239,
      name: "Trinidad and Tobago",
      image: "https://flagcdn.com/w320/tt.png",
      population: 1399491,
      capital: ["Port of Spain"],
      area: 5130,
    },
    {
      id: 240,
      name: "Puerto Rico",
      image: "https://flagcdn.com/w320/pr.png",
      population: 3194034,
      capital: ["San Juan"],
      area: 8870,
    },
    {
      id: 241,
      name: "Singapore",
      image: "https://flagcdn.com/w320/sg.png",
      population: 5685807,
      capital: ["Singapore"],
      area: 710,
    },
    {
      id: 242,
      name: "Hungary",
      image: "https://flagcdn.com/w320/hu.png",
      population: 9749763,
      capital: ["Budapest"],
      area: 93028,
    },
    {
      id: 243,
      name: "Costa Rica",
      image: "https://flagcdn.com/w320/cr.png",
      population: 5094114,
      capital: ["San José"],
      area: 51100,
    },
    {
      id: 244,
      name: "Israel",
      image: "https://flagcdn.com/w320/il.png",
      population: 9216900,
      capital: ["Jerusalem"],
      area: 20770,
    },
    {
      id: 245,
      name: "Bulgaria",
      image: "https://flagcdn.com/w320/bg.png",
      population: 6927288,
      capital: ["Sofia"],
      area: 110879,
    },
    {
      id: 246,
      name: "Azerbaijan",
      image: "https://flagcdn.com/w320/az.png",
      population: 10110116,
      capital: ["Baku"],
      area: 86600,
    },
    {
      id: 247,
      name: "Timor-Leste",
      image: "https://flagcdn.com/w320/tl.png",
      population: 1318442,
      capital: ["Dili"],
      area: 14874,
    },
    {
      id: 248,
      name: "Iran",
      image: "https://flagcdn.com/w320/ir.png",
      population: 83992953,
      capital: ["Tehran"],
      area: 1648195,
    },
    {
      id: 249,
      name: "Croatia",
      image: "https://flagcdn.com/w320/hr.png",
      population: 4047200,
      capital: ["Zagreb"],
      area: 56594,
    },
    {
      id: 250,
      name: "Ivory Coast",
      image: "https://flagcdn.com/w320/ci.png",
      population: 26378275,
      capital: ["Yamoussoukro"],
      area: 322463,
    },
  ],
  billionaires: [
    {
      id: 1,
      name: "Elon Musk",
      image: "https://images.lifestyleasia.com/wp-content/uploads/sites/6/2024/01/05003004/elon-musk-1536x864.jpeg"
    },
    {
      id: 2,
      name: "Bernard Arnault",
      image: "https://images.lifestyleasia.com/wp-content/uploads/sites/6/2024/01/05003015/bernard-arnault-1536x864.jpeg"
    },
    {
      id: 3,
      name: "Jeff Bezos",
      image: "https://images.lifestyleasia.com/wp-content/uploads/sites/6/2024/01/05003024/jeff-bezos-1536x864.jpeg",
    },
    {
      id: 4,
      name: "Larry Ellison",
      image: "https://images.lifestyleasia.com/wp-content/uploads/sites/6/2024/01/05003032/larry-ellison-1536x864.jpeg",
    },
    {
      id: 5,
      name: "Mark Zuckerberg",
      image: "https://images.lifestyleasia.com/wp-content/uploads/sites/6/2024/01/05003041/mark-zuckerberg-1536x864.jpeg",
    },
    {
      id: 6,
      name: "Warren Buffett",
      image: "https://images.lifestyleasia.com/wp-content/uploads/sites/6/2024/01/05003049/warren-buffett-1536x864.jpeg",
    },
    {
      id: 7,
      name: "Bill Gates",
      image: "https://images.lifestyleasia.com/wp-content/uploads/sites/6/2024/01/05003058/bill-gates.jpeg",
    },
    {
      id: 8,
      name: "Larry Page",
      image: "https://images.lifestyleasia.com/wp-content/uploads/sites/6/2024/01/05003105/larry-page.jpeg",
    },
    {
      id: 9,
      name: "Sergey Brin",
      image: "https://images.lifestyleasia.com/wp-content/uploads/sites/6/2024/01/05003112/sergey-brin-1536x864.jpeg",
    },
    {
      id: 10,
      name: "Steve Ballmer",
      image: "https://images.lifestyleasia.com/wp-content/uploads/sites/6/2024/01/05003120/steve-ballmer-1536x864.jpeg",
    },
  ],
};
